[rospy.client][INFO] 2020-10-30 00:11:22,320: init_node, name[/rostful_server], pid[7184]
[xmlrpc][INFO] 2020-10-30 00:11:22,320: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-10-30 00:11:22,320: Started XML-RPC server [http://freight1207:45575/]
[rospy.init][INFO] 2020-10-30 00:11:22,320: ROS Slave URI: [http://freight1207:45575/]
[rospy.impl.masterslave][INFO] 2020-10-30 00:11:22,320: _ready: http://freight1207:45575/
[xmlrpc][INFO] 2020-10-30 00:11:22,321: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-10-30 00:11:22,321: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-10-30 00:11:22,421: registered with master
[rospy.rosout][INFO] 2020-10-30 00:11:22,421: initializing /rosout core topic
[rospy.rosout][INFO] 2020-10-30 00:11:22,422: connected to core topic /rosout
[rospy.simtime][INFO] 2020-10-30 00:11:22,423: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][WARNING] 2020-10-30 00:11:22,427: rostful_server: Delaying the start 1 seconds
[rospy.internal][INFO] 2020-10-30 00:11:22,686: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,486: topic[/current/pose] adding connection to [http://freight1207:49314/], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,488: topic[/current/pose] adding connection to [http://freight1207:45575/], count 1
[rospy.internal][INFO] 2020-10-30 00:11:23,490: topic[/remote_control] adding connection to [http://freight1207:45575/], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,491: topic[/local_control/cancel] adding connection to [http://freight1207:45575/], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,491: topic[/current/pose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,492: topic[/remote_control] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,493: topic[/local_control/initialpose] adding connection to [http://freight1207:45575/], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,493: topic[/local_control/cancel] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,494: topic[/local_control/initialpose] adding connection to [/rostful_server], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,495: topic[/enable_software_runstop] adding connection to [http://freight1207:45575/], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,495: topic[/enable_software_runstop] adding connection to [/software_runstop], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,496: topic[/local_control/goto] adding connection to [http://freight1207:45575/], count 0
[rospy.internal][INFO] 2020-10-30 00:11:23,496: topic[/enable_software_runstop] adding connection to [/rostful_server], count 1
[rospy.internal][INFO] 2020-10-30 00:11:23,496: topic[/local_control/goto] adding connection to [/rostful_server], count 0
[rosout][INFO] 2020-10-30 00:11:23,554: rostful_server: Started server on port 8080
[rospy.internal][INFO] 2020-10-30 00:11:23,688: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 1
[rospy.internal][INFO] 2020-10-30 00:11:23,688: topic[/local_control/goto] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-10-30 00:11:23,689: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 1
[rospy.internal][INFO] 2020-10-30 00:11:23,689: topic[/remote_control] adding connection to [/remote_control], count 1
[rospy.internal][WARNING] 2020-10-30 00:11:30,109: Unknown error initiating TCP/IP socket to freight1207:60957 (http://freight1207:49314/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-10-30 00:11:30,109: topic[/current/pose] removing connection to http://freight1207:49314/
[rospy.internal][INFO] 2020-10-30 00:11:32,020: topic[/current/pose] adding connection to [http://freight1207:54778/], count 1
[rospy.internal][INFO] 2020-10-30 00:11:32,205: topic[/local_control/goto] adding connection to [/local_control_navigation], count 2
[rospy.internal][INFO] 2020-10-30 00:11:32,205: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-10-30 00:11:32,205: topic[/local_control/initialpose] adding connection to [/local_control_initialpose], count 2
[rospy.internal][INFO] 2020-10-30 00:11:32,205: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-10-30 00:11:32,205: topic[/local_control/cancel] adding connection to [/local_control_navigation], count 2
[rospy.internal][INFO] 2020-10-30 00:11:32,205: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-10-30 00:11:36,710: topic[/remote_control] adding connection to [/remote_control], count 2
[rospy.internal][INFO] 2020-10-30 00:11:36,710: topic[/remote_control] removing connection to /remote_control
[rosout][WARNING] 2020-10-30 00:11:39,113: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -0.87
    locationY: 0.48
    orientation: 0.9
  - 
    locationX: -0.01
    locationY: 2.41
    orientation: 0.9 to topic /local_control/goto
[rosout][WARNING] 2020-10-30 00:11:46,680: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -0.87
    locationY: 0.48
    orientation: 0.9
  - 
    locationX: -0.01
    locationY: 2.41
    orientation: 0.9 to topic /local_control/goto
[rosout][WARNING] 2020-10-30 00:11:52,386: publishing header: 
  seq: 0
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
goals: 
  - 
    locationX: -0.87
    locationY: 0.48
    orientation: 0.9
  - 
    locationX: -0.01
    locationY: 2.41
    orientation: 0.9 to topic /local_control/goto
[rospy.internal][WARNING] 2020-10-30 00:12:00,648: Unknown error initiating TCP/IP socket to freight1207:57714 (http://freight1207:54778/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-10-30 00:12:00,648: topic[/current/pose] removing connection to http://freight1207:54778/
[rosout][INFO] 2020-10-30 00:12:12,576: rostful_server: Shutting down the server
[rospy.core][INFO] 2020-10-30 00:12:12,576: signal_shutdown [Closing]
[rospy.internal][INFO] 2020-10-30 00:12:12,580: topic[/enable_software_runstop] removing connection to /software_runstop
[rospy.internal][INFO] 2020-10-30 00:12:12,580: topic[/enable_software_runstop] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-30 00:12:12,580: topic[/local_control/goto] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-30 00:12:12,580: topic[/local_control/goto] removing connection to /local_control_navigation
[rospy.internal][ERROR] 2020-10-30 00:12:12,581: Unable to initiate TCP/IP socket to freight1207:32840 (http://freight1207:45575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-30 00:12:12,581: topic[/rosout] removing connection to /rosout
[rospy.internal][ERROR] 2020-10-30 00:12:12,581: Unable to initiate TCP/IP socket to freight1207:32840 (http://freight1207:45575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-30 00:12:12,581: topic[/local_control/initialpose] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-30 00:12:12,581: topic[/local_control/initialpose] removing connection to /local_control_initialpose
[rospy.internal][INFO] 2020-10-30 00:12:12,582: topic[/remote_control] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-10-30 00:12:12,582: Unable to initiate TCP/IP socket to freight1207:32840 (http://freight1207:45575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-30 00:12:12,582: topic[/remote_control] removing connection to /remote_control
[rospy.internal][ERROR] 2020-10-30 00:12:12,582: Unable to initiate TCP/IP socket to freight1207:32840 (http://freight1207:45575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-30 00:12:12,582: topic[/local_control/cancel] removing connection to /rostful_server
[rospy.internal][INFO] 2020-10-30 00:12:12,582: topic[/local_control/cancel] removing connection to /local_control_navigation
[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/current/pose] removing connection to /rostful_server
[rospy.internal][ERROR] 2020-10-30 00:12:12,583: Unable to initiate TCP/IP socket to freight1207:32840 (http://freight1207:45575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/enable_software_runstop] removing connection to http://freight1207:45575/
[rospy.internal][ERROR] 2020-10-30 00:12:12,583: Unable to initiate TCP/IP socket to freight1207:32840 (http://freight1207:45575/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/local_control/goto] removing connection to http://freight1207:45575/
[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/local_control/initialpose] removing connection to http://freight1207:45575/
[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/remote_control] removing connection to http://freight1207:45575/
[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/local_control/cancel] removing connection to http://freight1207:45575/
[rospy.internal][INFO] 2020-10-30 00:12:12,583: topic[/current/pose] removing connection to http://freight1207:45575/
[rospy.impl.masterslave][INFO] 2020-10-30 00:12:12,583: Closing
[rospy.core][INFO] 2020-10-30 00:12:12,715: signal_shutdown [atexit]
