[rospy.client][INFO] 2020-11-01 23:02:16,366: init_node, name[/rostopic_15473_1604300536345], pid[15473]
[xmlrpc][INFO] 2020-11-01 23:02:16,366: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-01 23:02:16,366: Started XML-RPC server [http://freight1207:43795/]
[rospy.init][INFO] 2020-11-01 23:02:16,367: ROS Slave URI: [http://freight1207:43795/]
[rospy.impl.masterslave][INFO] 2020-11-01 23:02:16,367: _ready: http://freight1207:43795/
[rospy.registration][INFO] 2020-11-01 23:02:16,367: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-11-01 23:02:16,367: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-11-01 23:02:16,467: registered with master
[rospy.rosout][INFO] 2020-11-01 23:02:16,467: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-01 23:02:16,468: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-01 23:02:16,469: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-01 23:02:16,481: topic[/amcl_pose] adding connection to [http://freight1207:45957/], count 0
[rospy.internal][INFO] 2020-11-01 23:02:16,678: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2020-11-01 23:03:28,271: Unable to initiate TCP/IP socket to freight1207:35439 (http://freight1207:45957/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/amcl_pose] from [TCPROS connection on port 35439 to [127.0.0.1:34744 on socket 3]] [/rostopic_15473_1604300536345].

[rospy.internal][WARNING] 2020-11-01 23:03:29,273: Unknown error initiating TCP/IP socket to freight1207:35439 (http://freight1207:45957/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-11-01 23:03:29,273: topic[/amcl_pose] removing connection to http://freight1207:45957/
[rospy.core][INFO] 2020-11-01 23:03:48,229: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-01 23:03:48,231: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-11-01 23:03:48,231: signal-2
[rospy.core][INFO] 2020-11-01 23:03:48,395: signal_shutdown [atexit]
