[rospy.client][INFO] 2020-11-01 22:29:21,441: init_node, name[/rostopic_9447_1604298561420], pid[9447]
[xmlrpc][INFO] 2020-11-01 22:29:21,441: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-11-01 22:29:21,441: Started XML-RPC server [http://freight1207:60645/]
[rospy.init][INFO] 2020-11-01 22:29:21,441: ROS Slave URI: [http://freight1207:60645/]
[rospy.impl.masterslave][INFO] 2020-11-01 22:29:21,441: _ready: http://freight1207:60645/
[xmlrpc][INFO] 2020-11-01 22:29:21,442: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-11-01 22:29:21,442: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-11-01 22:29:21,542: registered with master
[rospy.rosout][INFO] 2020-11-01 22:29:21,542: initializing /rosout core topic
[rospy.rosout][INFO] 2020-11-01 22:29:21,543: connected to core topic /rosout
[rospy.simtime][INFO] 2020-11-01 22:29:21,544: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-11-01 22:29:21,556: topic[/amcl_pose] adding connection to [http://freight1207:49767/], count 0
[rospy.internal][INFO] 2020-11-01 22:29:21,807: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][ERROR] 2020-11-01 22:31:54,328: Unable to initiate TCP/IP socket to freight1207:54382 (http://freight1207:49767/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: received a connection for a nonexistent topic [/amcl_pose] from [TCPROS connection on port 54382 to [127.0.0.1:49666 on socket 9]] [/rostopic_9447_1604298561420].

[rospy.internal][WARNING] 2020-11-01 22:31:55,330: Unknown error initiating TCP/IP socket to freight1207:54382 (http://freight1207:49767/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2020-11-01 22:31:55,330: topic[/amcl_pose] removing connection to http://freight1207:49767/
[rospy.core][INFO] 2020-11-01 22:32:10,578: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-11-01 22:32:10,580: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2020-11-01 22:32:10,580: signal-2
[rospy.core][INFO] 2020-11-01 22:32:10,696: signal_shutdown [atexit]
